name: Go

on:
  release:
      types: 
        - created

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Download Deps
      run: |
        go get -d -v ./...
        go install -v ./...

    - name: Build Linux
      run: |
        go build cmd/mp3fileInfo.go
        zip -r mp3fileInfo_linux.zip mp3fileInfo

    - name: Build Windows
      run: | 
        GOOS=windows GOARCH=amd64 go build cmd/mp3fileInfo.go
        zip -r mp3fileInfo_windows.zip mp3fileInfo.exe
        
    - name: Upload assets - linux
      id: upload-release-asset-linux 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./mp3fileInfo_linux.zip
        asset_name: ./mp3fileInfo_linux.zip
        asset_content_type: application/zip

    - name: Upload assets - windows
      id: upload-release-asset-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./mp3fileInfo_windows.zip
        asset_name: ./mp3fileInfo_windows.zip
        asset_content_type: application/zip
